name: AutoUpdateLantern

on:
  # 测试用
  watch:
    types: started
  # 每天更新
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run check_update.sh
      run: |
        chmod +x ./check_update.sh
        ./check_update.sh

